services:
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: development

  frontend:
    build:
      target: development
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      API_PROXY_TARGET: http://backend:8000
